server:
  port: 9080

spring:
  mail:
    host: smtp.office365.com
    port: 587
    username: inserirSeuEmail@hotmail.com
    password: inserirSuaSenha
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: false


  rabbitmq:
    addresses: inserir a url da instância criada no RabbitMQ

queue:
  fiap:
    userVhost: inserir Vhost
    password: inserir senha
    port: inserir número da porta
    url: inserir a url da instância criada no RabbitMQ
    nome: fiap.1scjr.drone



